# .
# .  读取教程: http://dev.bukkit.org/bukkit-plugins/holographic-displays/
# .
# . 插件制作： filoghost.
# .
space-between-lines: 0.02
images:
  symbol: '[x]'
  transparency:
    space: ' [|] '
    color: '&7'
bungee:
  refresh-seconds: 3
  use-RedisBungee: false
  pinger:
    enable: false
    timeout: 500
    offline-motd: '&cOffline, couldn''t get the MOTD.'
    status:
      online: '&aOnline'
      offline: '&cOffline'
    motd-remove-leading-trailing-spaces: true
    servers:
    - 'hub: 127.0.0.1:25565'
    - 'survival: 127.0.0.1:25566'
    - 'minigames: 127.0.0.1:25567'
time:
  format: H:mm
  zone: GMT+1
update-notification: false
debug: false
